// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using NUnit.Framework;
[TestFixture]
public class LoginTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void login() {
    /*
    Steps:
    Step 1: Launch Demo webiste
    Step 2: Click on My Account -> Login button
    Step 3: Enter valid username and password
    Step 4: Click on Login button
    
    Expectation: Navigate to user account details page
    */
    
    driver.Navigate().GoToUrl("https://www.phptravels.net/home");
    driver.Manage().Window.Size = new System.Drawing.Size(1440, 803);
    driver.FindElement(By.CssSelector(".dropdown-login > #dropdownCurrency")).Click();
    driver.FindElement(By.LinkText("Login")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) > .pure-material-textfield-outlined > span")).Click();
    driver.FindElement(By.Name("username")).SendKeys("user@phptravels.com");
    driver.FindElement(By.Name("password")).SendKeys("demouser");
    driver.FindElement(By.CssSelector(".btn-lg")).Click();
    Thread.Sleep(1000);
    
    String expectedURL = "https://www.phptravels.net/account/";
    String currentURL =  driver.Url;
    Assert.That(currentURL, Is.EqualTo(expectedURL));
  }
}
